version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=zenthic
      - POSTGRES_PASSWORD=zenthicpass
      - POSTGRES_DB=zenthic_crm
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U zenthic -d zenthic_crm"]
      interval: 10s
      timeout: 5s
      retries: 5

  chromadb:
    image: chromadb/chroma
    restart: always
    volumes:
      - chroma_data:/chroma/chroma
    ports:
      - "8001:8000"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=postgresql://zenthic:zenthicpass@db:5432/zenthic_crm
      - CHROMA_HOST=chromadb
      - CHROMA_PORT=8000
    depends_on:
      db:
        condition: service_healthy
      chromadb:
        condition: service_started

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend

volumes:
  postgres_data:
  chroma_data: